-- 샘플 테이블 생성
CREATE TABLE SAMPLE_TABLE (
    ID NUMBER(19) NOT NULL,
    CONTENT VARCHAR2(1000),
    STATUS VARCHAR2(20),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_SAMPLE_TABLE
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

-- 테스트 데이터 삽입
INSERT INTO SAMPLE_TABLE (ID, CONTENT, STATUS) 
VALUES (SEQ_SAMPLE_TABLE.NEXTVAL, '샘플 데이터 1', 'ACTIVE');

INSERT INTO SAMPLE_TABLE (ID, CONTENT, STATUS) 
VALUES (SEQ_SAMPLE_TABLE.NEXTVAL, '샘플 데이터 2', 'ACTIVE');

INSERT INTO SAMPLE_TABLE (ID, CONTENT, STATUS) 
VALUES (SEQ_SAMPLE_TABLE.NEXTVAL, '샘플 데이터 3', 'INACTIVE');

COMMIT; 